// app/dashboard/layout.tsx
import type React from "react";
import { DashboardSidebar } from "@/components/dashboard/sidebar";
import { DashboardHeader } from "@/components/dashboard/header";
import { SidebarProvider } from "@/components/ui/sidebar";
import { NavigationOverlay } from "@/components/navigation/navigation-overlay";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { ProtectedRoute } from "@/components/auth/protected-route";

export const metadata: Metadata = {
  title: "Buzz | Saas",
  description: "Generated by rbxyz",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute>
      <SidebarProvider>
        <div className="bg-background text-foreground flex min-h-screen w-full flex-col">
          <DashboardHeader />

          <div className="flex min-h-0 flex-1 overflow-hidden">
            {/* Sidebar fixo com largura 64 (256px) */}
            <DashboardSidebar />

            {/* Área principal, com padding para "não ficar atrás do sidebar" */}
            <main className="flex-1 overflow-y-auto p-4 md:p-6 md:pl-64">
              {children}
            </main>
          </div>

          {/* Overlay de navegação global */}
          <NavigationOverlay />
          <Toaster />
        </div>
      </SidebarProvider>
    </ProtectedRoute>
  );
}
