// app/dashboard/layout.tsx
import type React from "react";
import { DashboardSidebar } from "@/components/dashboard/sidebar";
import { DashboardHeader } from "@/components/dashboard/header";
import { SidebarProvider } from "@/contexts/sidebar-context";
import { NavigationOverlay } from "@/components/navigation/navigation-overlay";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { ProtectedRoute } from "@/components/auth/protected-route";

export const metadata: Metadata = {
  title: "Buzz | Saas",
  description: "Generated by rbxyz",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ProtectedRoute>
      <SidebarProvider>
        <div className="min-h-screen bg-background">
          <DashboardSidebar />
          <div className="transition-all duration-300 ease-smooth md:pl-64">
            <DashboardHeader />
            <div className="p-4 sm:p-6 lg:p-8">{children}</div>
          </div>
          <NavigationOverlay />
          <Toaster />
        </div>
      </SidebarProvider>
    </ProtectedRoute>
  );
}
